# Generated by Django 4.2.2 on 2024-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('pubdate', models.DateField()),
                ('author', models.TextField()),
                ('pricesales', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('publisher', models.TextField()),
                ('salesPoint', models.IntegerField()),
            ],
        ),
    ]
